AWSTemplateFormatVersion: '2010-09-09'
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "email"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "users"

  DoctorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "license_number"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "license_number"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "doctors"

  HospitalsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "hospital_id"
          AttributeType: "S"
        -
          AttributeName: "pincode"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "pincode"
          KeyType: "HASH"
        -
          AttributeName: "hospital_id"
          KeyType: "RANGE"

      BillingMode: "PAY_PER_REQUEST"
      TableName: "hospitals"

  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "user_id"
          AttributeType: "S"
        -
          AttributeName: "appointment_time"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "user_id"
          KeyType: "HASH"
        -
          AttributeName: "appointment_time"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "appointments"